plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0' // или какая там точная версия на экране, обычно 4.x.x
    implementation 'org.testng:testng:7.11.0'
}


test {
    useTestNG()
}